services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=authentication_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=codecrafters'
    ports:
      - '5440:5432'
  authentication:
    build:
      context: .
    environment:
      DATABASE_URL: 'postgresql://postgres:codecrafters@authentication_db/authentication_db'
    depends_on:
      - 'postgres'
    ports:
      - "8082:8082"
